version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - PORT=${PORT:-8000}
    volumes:
      - .:/app
      - ollama_models:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  ollama_models:
    driver: local
